version: "2"
services:
  meditor:
    image: moravianlibrary/meditor
    env_file: meditor.env
    volumes:
      - /data/meditor:/data/meditor
      - /data/imageserver:/data/imageserver
    ports:
      - "80:8080"
      - "443:8443"
  meditorPostgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=meditor
      - POSTGRES_PASSWORD=meditor
      - POSTGRES_DB=meditor
    ports:
      - "5432:5432"
  ldap:
    image: nickstenning/slapd
    environment:
      -  LDAP_DOMAIN=medit.mzk.cz
      -  LDAP_ORGANISATION="MZK"
      -  LDAP_ROOTPASS=s3cr3tpassw0rd
    volumes:
      - /data/meditor/ldap/etc:/etc/ldap/slapd.d
      - /data/meditor/ldap/ldap:/var/lib/ldap/
  phpldapadmin:
    image: windfisch/phpldapadmin
    environment:
      -  LDAP_HOST=ldap
      -  LDAP_BASE_DN=dc=medit,dc=mzk,dc=cz
      -  LDAP_LOGIN_DN=cn=admin,dc=medit,dc=mzk,dc=cz
    ports:
      - "444:443"
