version: "2"
services:
  meditor:
    image: meditor
    environment:
     - identities=ldap
     - dbName=meditor
     - dbHost=meditorPostgres
     - dbPassword=meditor
     - oaiUrls=https://aleph.mzk.cz/OAI
     - "oaiIdPrefixes=oai:aleph.mzk.cz:"
     - oaiRecordIdentifierLength=variable
     - fedoraHost=http://fcrepo:8080/fedora
     - fedoraLogin=fedoraAdmin
     - fedoraPassword=fedoraAdmin
     - fedoraVersion=3.8.1
     - krameriusHost=http://kramerius:8080/search/
     - krameriusLogin=krameriusAdmin
     - krameriusPassword=krameriusAdmin
     - imageServer.url=http://imageserver/
     - imageServer.known=/data/imageserver/
     - imageServer.unknown=/data/imageserver/meditor/
     - imageExtension=jpg, JPG, png, tiff, tif, jpeg, jp2, pdf
     - inputQueue=/data/meditor/import
     - KEYCLOAK_REALM=meditor
     - KEYCLOAK_RESOURCE=meditor
     - "KEYCLOAK_REALM_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgu2/6IqWcCzImbF+cv7TrN5+2ctvw6cgoND7F4DRlQamzE6ShjWQ5I/V+okMN1+1RJl6BVBfC2bKdEpc0mUxSk/jgQYHiSBjjH7Qvy7yFDNxZ3I20xY8WtJzFPhs3g46TE57beCVJNU9y4eGVt8zO5+0SrCxuXrOnd7tU/0zNq1VXuOFlb8ctSpFioM2+QgCgonhYC0Bhr/Ry999a569OfPq7ua4QnPQBE2tVicJYScVvyjEMCi4sjj4beMYaBjyshIUD4Z07yQAP4RAeh4bzfQoNbQDykEcpF+oU29fIqQFWGJTfskSfHNCN33wLGa/JLdylSjTRPNN1vxSGMqrnQIDAQAB"
     - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth/
     - KEYCLOAK_SECRET=password
    volumes:
      - /data/meditor:/data/meditor
      - /data/imageserver:/data/imageserver
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - meditor
  meditorPostgres:
    image: "postgres:9.3"
    environment:
      - POSTGRES_USER=meditor
      - POSTGRES_PASSWORD=meditor
      - POSTGRES_DB=meditor
    ports:
      - "5432:5432"
    networks:
      - meditor
  keycloak:
   image: jboss/keycloak
   environment:
     - KEYCLOAK_USER=medit
     - KEYCLOAK_PASSWORD=medit
   ports:
     - "8080:8080"
   networks:
     - meditor
networks:
  meditor:
    driver: bridge
